###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Henrique Miranda, Alejandro Molina Sánchez, Fulvio Paleari, Riccardo Reho'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2024, Henrique Miranda, Alejandro Molina Sánchez, Fulvio Paleari, Riccardo Reho'
exclude_patterns = ['build', 'Thumbs.db', '.DS_Store']
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx_jupyterbook_latex',
    'sphinx_multitoc_numbering',
    'sphinxcontrib.bibtex',
    'sphinx_proof'
]
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = '../logos/yambopy_square.png'
html_logo = ''
html_sidebars = {'**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']}
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': '', 'deepnote_url': ''}, 'path_to_docs': '', 'repository_url': 'https://github.com/executablebooks/jupyter-book', 'repository_branch': 'master', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': '', 'plausible_analytics_domain': '', 'plausible_analytics_url': 'https://plausible.io/js/script.js'}, 'use_repository_button': False, 'use_edit_page_button': False, 'use_issues_button': False}
html_title = 'QuREX Documentation'
latex_engine = 'pdflatex'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = 'auto'
nb_execution_timeout = 30
nb_output_stderr = 'show'
numfig = True
project = 'yambopy'
pygments_style = 'sphinx'
release = '3.0.0'
suppress_warnings = ['myst.domains']
sys_path = ['../../yambopy']
templates_path = ['_templates']
use_jupyterbook_latex = True
use_multitoc_numbering = True
